#!/usr/bin/env python

import re
from operator import itemgetter

import pf
import printer
import rdata
from args import ARGS
from formatting import com
from formatting import prefix
from formatting import space


def ac(ac):
  return space(f"AC {ac['value']}", ac['details'])

def print_creature(data, printer):
  printer.print_title(data['name']);
  stm = data['system']

  printer.print(com(
    pf.level(stm['details']['level']),
    stm['traits']['size']['value'],
    stm['traits']['rarity'],
    *stm['traits']['value'],
  ))

  abl = stm['abilities']
  stats = [f"{a.upper()} {abl[a]['mod']}" for a in ['str', 'dex', 'con', 'int', 'wis', 'cha']]
  printer.print(com(*stats))

  atr = stm['attributes']
  os = ''
  if atr['speed']['otherSpeeds']:
    os = [f"{os['type']} {os['value']}" for os in atr['speed']['otherSpeeds']]
    os = f" ({com(*os)})"
  printer.print(f"{ac(atr['ac'])}, HP {atr['hp']['value']}, speed {atr['speed']['value']}{os}")

  perc = stm['perception']
  sens = [space(a['type'], a['range'], a['acuity']) for a in perc['senses']]
  printer.print(f"perc {perc['mod']} ({com(*sens)})")

  svs = stm['saves']
  stats = [f"{a[:4]} {svs[a]['value']}{svs[a]['saveDetail']}" for a in ['fortitude', 'reflex', 'will']]
  printer.print(com(*stats))

  printer.print_item("immune:", com(*[i['type'] for i in atr['immunities']]))
  printer.print_item("weak:", com(*[
    space(
      w['type'],
      w['value'],
      prefix(com(*[e for e in w['exceptions']]), "except "),  # untested
      )
    for w in atr['weaknesses']]))

  lang = stm['details']['languages']
  printer.print_item("lang:", com(*lang['value'], lang['details']))

  # TODO skills

  items = sorted(data['items'], key=itemgetter('sort'), reverse=True)
  for i in items:
    s = i['system']

    marker = (' ' * 10) + pf.actions(s)
    marker = f"{marker[-10:]} "

    title = i['name']

    if 'bonus' in s:
      title += f" +{s['bonus']['value']}"

    if 'damageRolls' in s:
      dmg = [f"{d['damage']}{d['damageType'][0]}" for d in s['damageRolls'].values()]
      title += f" {com(*dmg)}"

    if s['level']:
      title += f" {pf.level(s['level'])}"

    if s['duration']['sustained']:
      title += f" (sustained)"
    if s['duration']['value']:
      title += f" ({s['duration']['value']})"

    if s['attackEffects']['value']:
      title += f" --> {com(*s['attackEffects']['value'])}"

    i['heading'] = printer.render_item(marker, title)
    printer.print(i['heading'])

  if not ARGS.show_details:
    return

  printer.print_heading_and_html([
    (i['heading'], pf.remove_macros_html(i['system']['description']['value']))
    for i in items])


data = rdata.read_json()
with printer.Printer() as p:
  print_creature(data, p)
