#!/usr/bin/env python

import re
from operator import itemgetter

import misc
import printer
import rdata
from args import ARGS
from misc import com
from misc import prefix
from misc import space


def parse_actions(t):
  if t == 'reaction':
    return '<-'
  elif t == 'passive':
    return '-'
  elif t == "1 to 3":
    return '*/**/***'
  else:
    m = re.match(r"(\d+) *(minutes?|hours?|days?)", str(t))
    if m:
      return f"{m.group(1)}{m.group(2)[:1]}"

    try:
      return '*' * int(t)
    except ValueError:
      return t

def ac(ac):
  return space(f"AC {ac['value']}", ac['details'])

def print_creature(data, printer):
  printer.print(data['name']);
  stm = data['system']

  abl = stm['abilities']
  stats = [f"{a.upper()} {abl[a]['mod']}" for a in ['str', 'dex', 'con', 'int', 'wis', 'cha']]
  printer.print(', '.join(stats))

  atr = stm['attributes']
  os = ''
  if atr['speed']['otherSpeeds']:
    os = [f"{os['type']} {os['value']}" for os in atr['speed']['otherSpeeds']]
    os = f" ({', '.join(os)})"
  printer.print(f"{ac(atr['ac'])}, HP {atr['hp']['value']}, speed {atr['speed']['value']}{os}")

  perc = stm['perception']
  sens = [space(a['type'], a['range'], a['acuity']) for a in perc['senses']]
  printer.print(f"perc {perc['mod']} ({com(*sens)})")

  svs = stm['saves']
  stats = [f"{a[:4]} {svs[a]['value']}{svs[a]['saveDetail']}" for a in ['fortitude', 'reflex', 'will']]
  printer.print(', '.join(stats))

  imu = atr['immunities']
  if imu:
    printer.print(space("immune:", com(*[i['type'] for i in imu])))

  weak = atr['weaknesses']
  if weak:
    printer.print(space("weak:", com(*[
      space(
        w['type'],
        w['value'],
        prefix(com([e for e in w['exceptions']]), "except "),  # untested
        )
      for w in weak])))

  lang = stm['details']['languages']
  if lang:
    printer.print(space(
      "lang:",
      com(*lang['value']),
      lang['details'],
      ))

  # TODO skills

  items = sorted(data['items'], key=itemgetter('sort'), reverse=True)
  for i in items:
    s = i['system']

    marker = ' ' * 10
    if s['actions']['value']:
      marker += parse_actions(s['actions']['value'])
    elif s['actionType']['value']:
      marker += parse_actions(s['actionType']['value'])
    elif s['time']['value']:
      marker += parse_actions(s['time']['value'])
    else:
      marker += '*'
    marker = f"{marker[-10:]} "

    title = i['name']

    if 'bonus' in s:
      title += f" +{s['bonus']['value']}"

    if 'damageRolls' in s:
      dmg = [f"{d['damage']}{d['damageType'][0]}" for d in s['damageRolls'].values()]
      title += f" {', '.join(dmg)}"

    if s['level']:
      title += f" {misc.level(s['level'])}"

    if s['duration']['sustained']:
      title += f" (sustained)"
    if s['duration']['value']:
      title += f" ({s['duration']['value']})"

    if s['attackEffects']['value']:
      title += f" --> {', '.join(s['attackEffects']['value'])}"

    i['heading'] = printer.render_item(marker, title)
    printer.print(i['heading'])

  if not ARGS.show_details:
    return

  printer.print_heading_and_html([
    (i['heading'], misc.remove_macros(i['system']['description']['value']))
    for i in items])


data = rdata.read_json()
with printer.Printer() as p:
  print_creature(data, p)
