#!/usr/bin/env python

import re
from operator import itemgetter

import pf
import printer
import rdata
from formatting import com
from formatting import space
from formatting import suffix

def price(p):
  v = p['value']
  if not v:
    return None
  return space(*[f"{v[c]}{c}" for c in ['pp', 'gp', 'sp', 'cp'] if v[c]])

def hp(h):
  v = h['value']
  m = h['max']
  if v:
    if v == m or not m:
      return f"{v} hp"
    return f"{v}/{m} hp"
  if m:
    return f"{m} hp"
  return None

def print_item(data, printer):
  stm = data['system']

  printer.print_title(data['name'])
  printer.print(com(
    suffix(stm['acBonus'], 'AC'),
    suffix(stm['checkPenalty'], 'CP'),
    stm['category'],
    pf.level(stm['level']),
    price(stm['price']),
    suffix(stm['bulk']['value'], 'bulk'),
    suffix(stm['hardness'], 'hrd'),
    hp(stm['hp']),
    ))

  #TODO material quantity uses

  printer.print(com(
    pf.damage(stm['meleeUsage']['damage']),
    pf.damage(stm['damage']),
    ))

  printer.print(com(
    stm['traits']['rarity'],
    *stm['traits']['value'],
    ))


  printer.print_hr()
  printer.print_html(pf.remove_macros_html(stm['description']['value']))


data = rdata.read_json()
with printer.Printer() as p:
  print_item(data, p)
