#!/usr/bin/env python

import re
from operator import itemgetter

import common
import printer
import rdata
from common import space

def price(p):
  v = p['value']
  if not v:
    return None
  return space(*[f"{v[c]}{c}" for c in ['pp', 'gp', 'sp', 'cp'] if v[c]])

def suffix(val, suf):
  if not val:
    return ''
  return f"{val} {suf}"

def hp(h):
  v = h['value']
  m = h['max']
  if v:
    if v == m or not m:
      return f"{v} hp"
    return f"{v}/{m} hp"
  if m:
    return f"{m} hp"
  return None

def print_item(data, printer):
  stm = data['system']

  printer.print(data['name']);
  printer.print(space(
    suffix(stm['acBonus'], 'AC'),
    suffix(stm['checkPenalty'], 'CP'),
    stm['category'],
    common.level(stm['level']),
    price(stm['price']),
    suffix(stm['bulk']['value'], 'bulk'),
    suffix(stm['hardness'], 'hrd'),
    hp(stm['hp']),
    sep=', '));

  #TODO material quantity uses

  dmg = stm['damage']
  if dmg:
    printer.print(f"{dmg['formula']} ({space(dmg['kind'], dmg['type'], sep=', ')})");

  printer.print_hr()
  printer.print_html(common.remove_macros(stm['description']['value']))


data = rdata.read_json()
with printer.Printer() as p:
  print_item(data, p)
