#!/usr/bin/env python

import re
from operator import itemgetter

import misc
import printer
import rdata
from misc import com
from misc import space
from misc import suffix

def price(p):
  v = p['value']
  if not v:
    return None
  return space(*[f"{v[c]}{c}" for c in ['pp', 'gp', 'sp', 'cp'] if v[c]])

def hp(h):
  v = h['value']
  m = h['max']
  if v:
    if v == m or not m:
      return f"{v} hp"
    return f"{v}/{m} hp"
  if m:
    return f"{m} hp"
  return None

def damage(d):
  if not d:
    return None
  amt = space(
    d['formula'],
    f"{d['dice']}{d['die']}" if d['die'] else None,
    )
  if not amt:
    return None
  typ = com(d['kind'], d['type'], d['damageType'])
  return f"{amt} ({typ})"

def print_item(data, printer):
  stm = data['system']

  printer.print_title(data['name']);
  printer.print(com(
    suffix(stm['acBonus'], 'AC'),
    suffix(stm['checkPenalty'], 'CP'),
    stm['category'],
    misc.level(stm['level']),
    price(stm['price']),
    suffix(stm['bulk']['value'], 'bulk'),
    suffix(stm['hardness'], 'hrd'),
    hp(stm['hp']),
    ));

  #TODO material quantity uses

  printer.print(com(
    damage(stm['meleeUsage']['damage']),
    damage(stm['damage']),
    ))

  printer.print(com(
    stm['traits']['rarity'],
    *stm['traits']['value'],
    ))


  printer.print_hr()
  printer.print_html(misc.remove_macros(stm['description']['value']))


data = rdata.read_json()
with printer.Printer() as p:
  print_item(data, p)
