#!/usr/bin/env python

from operator import itemgetter

import dice
import pf
import printer
import rdata
from args import ARGS
from formatting import com
from formatting import space
from formatting import suffix

ARGS.add_argument("--rank", type=int)


def duration(d):
  if not d['sustained']:
    return None
  return d['value']

def get_heightening(stm):
  if not ARGS.rank:
    return (None, None)
  if not stm['heightening']:
    raise Exception(f"heightening not supported.")
  if ARGS.rank <= stm['level']['value']:
    raise Exception(f"heightening rank is less than spell rank.")

  heightening = stm['heightening']
  typ = heightening['type']
  if typ == 'interval':
    mul = (ARGS.rank - stm['level']['value']) / heightening['interval']
    if not mul.is_integer():
      raise Exception(f"invalid heightening rank: {ARGS.rank}")
    mul = int(mul)
    return (mul, heightening)
  elif typ == 'fixed':
    h = heightening['levels'][str(ARGS.rank)]
    if not h:
      raise Exception(f"rank {ARGS.rank} not defined for heightening, "
                      f"only: {list(heightening['levels'].keys())}")
    return (None, h)

  raise Exception(f"unknown heightening type: {typ}")

def heighten_damage(stm):
  damage = stm['damage']
  hmul, h = get_heightening(stm)
  if not h:
    return [pf.damage(v) for (k, v) in damage.items()]
  if hmul:
    return [pf.damage(d, dice.parse(h['damage'][k]).mul(hmul)) for k, d in damage.items()]
  return [pf.damage(h['damage'][k]) for k, d in damage.items()]

def heighten_target(stm):
  _, h = get_heightening(stm)
  return h['target']['value'] if h else stm['target']['value']

def heighten_range(stm):
  _, h = get_heightening(stm)
  return h['range']['value'] if h else stm['range']['value']

def heighten_area(stm):
  val = stm['area']['value']
  typ = stm['area']['type']

  hmul, h = get_heightening(stm)
  if h and h['area'] != 0:
    if hmul and h['area']:
      val += hmul * h['area']
    else:
      val = h['area']['value']
      typ = h['area']['type']

  return space(val, typ)

def print_spell(data, printer):
  stm = data['system']

  actions = pf.actions(stm)
  printer.print_title(space(data['name'], actions));
  # TODO is ritual?

  # TODO heighten target
  printer.print(com(
    f"R{ARGS.rank}" if ARGS.rank else pf.level(stm['level'], letter="R"),
    heighten_target(stm),
    heighten_range(stm),
    heighten_area(stm),
    duration(stm['duration']),
    ));

  printer.print(com(
    *heighten_damage(stm),
    ));

  printer.print(com(
    stm['traits']['rarity'],
    *stm['traits']['traditions'],
    *stm['traits']['value'],
    ))

  printer.print_hr()
  printer.print_html(pf.remove_macros_html(stm['description']['value']))


data = rdata.read_json()
with printer.Printer() as p:
  print_spell(data, p)
