#!/usr/bin/env python
import sys
from args import ARGS
from escpos import printer

ARGS.add_argument("--profile", dest='print_profile', default="TM-T88II")
ARGS.add_argument("--printer", dest='print_addr')

if ARGS.print_addr:
  p = printer.Network(ARGS.print_addr, profile=ARGS.print_profile)
else:
  p = printer.Dummy(profile=ARGS.print_profile)

def prt(data):
  output = []
  for b in data:
    if isinstance(b, int):
      output.append(bytes([b]))
    elif isinstance(b, bytes):
      output.append(b)
    else:
      raise ValueException()
  p._raw(b"".join(output))

def mkchar(cols, rows, data):
  s = [data[i:i + cols] for i in range(0, len(data), cols)]
  if len(s) != rows:
    raise ValueError(f"wrong number of rows: {len(s)}")

  output = b""
  for col in range(0, cols):
    for row in range(0, 3):
      byte = ""
      for bit in range(0, 8):
        y = row * 8 + bit
        if y >= rows:
          byte += "0"
        else:
          byte += "0" if s[row * 8 + bit][col] == " " else "1"
      output += bytes([int(byte, 2)])
  return output


pf_1act_a = mkchar(12, 24,
    "            "  #  0
    "            "  #  1
    "            "  #  2
    "            "  #  3
    "            "  #  4
    "            "  #  5
    "     xx     "  #  6
    "    xxxx    "  #  7
    "   xxxxxx   "  #  8
    "    xxxxxx  "  #  9
    " xx  xxxxxx "  # 10
    "xxxx  xxxxxx"  # 11
    "xxxx  xxxxxx"  # 12
    " xx  xxxxxx "  # 13
    "    xxxxxx  "  # 14
    "   xxxxxx   "  # 15
    "    xxxx    "  # 16
    "     xx     "  # 17
    "            "  # 18
    "            "  # 19
    "            "  # 20
    "            "  # 21
    "            "  # 22
    "            "  # 23
    )
pf_1act_b = mkchar(12, 24,
    "            "  #  0
    "            "  #  1
    "            "  #  2
    "            "  #  3
    "            "  #  4
    "            "  #  5
    "            "  #  6
    "            "  #  7
    "            "  #  8
    "     xx     "  #  9
    "    xxxx    "  # 10
    "   xxxxxx   "  # 11
    "    xxxxxx  "  # 12
    " xx  xxxxxx "  # 13
    "xxxx  xxxxxx"  # 14
    "xxxx  xxxxxx"  # 15
    " xx  xxxxxx "  # 16
    "    xxxxxx  "  # 17
    "   xxxxxx   "  # 18
    "    xxxx    "  # 19
    "     xx     "  # 20
    "            "  # 21
    "            "  # 22
    "            "  # 23
    )
box = mkchar(12, 24,
    "xxxxxxxxxxxx"  #  0
    "x          x"  #  1
    "x          x"  #  2
    "x          x"  #  3
    "x          x"  #  4
    "x          x"  #  5
    "x          x"  #  6
    "x          x"  #  7
    "x          x"  #  8
    "x          x"  #  9
    "x          x"  # 10
    "x          x"  # 11
    "x          x"  # 12
    "x          x"  # 13
    "x          x"  # 14
    "x          x"  # 15
    "x          x"  # 16
    "x          x"  # 17
    "x          x"  # 18
    "x          x"  # 19
    "x          x"  # 20
    "x          x"  # 21
    "x          x"  # 22
    "xxxxxxxxxxxx"  # 23
    )

print(pf_1act_a.hex())
print(pf_1act_b.hex())
print(box.hex())

p.set_with_default(font="a")
prt([0x1b, b"&", 3, b"A", b"A"])
prt([12])
prt(pf_1act_a)

prt([0x1b, b"%", 0])
prt(b"A B C D E ")
prt([0x1b, b"%", 1])
prt(b"A B C D E")
prt([0x0a])

p.set(font="b")
prt([0x1b, b"&", 3, b"A", b"A"])
prt([12])
prt(pf_1act_b)

prt([0x1b, b"%", 0])
prt(b"A B C D E ")
prt([0x1b, b"%", 1])
prt(b"A B C D E")
prt([0x0a])

p.cut()

if not ARGS.print_addr:
  print(p.output)
