#!/usr/bin/env python
import sys
from args import ARGS
from escpos import printer
from udchar import Udchars

ARGS.add_argument("--profile", dest='print_profile', default="TM-T88II")
ARGS.add_argument("--printer", dest='print_addr')

if ARGS.print_addr:
  p = printer.Network(ARGS.print_addr, profile=ARGS.print_profile)
else:
  p = printer.Dummy(profile=ARGS.print_profile)

def prt(data):
  output = []
  for b in data:
    if isinstance(b, int):
      output.append(bytes([b]))
    elif isinstance(b, bytes):
      output.append(b)
    else:
      raise ValueException()
  p._raw(b"".join(output))

def mkchar(cols, rows, data):
  s = [data[i:i + cols] for i in range(0, len(data), cols)]
  if len(s) != rows:
    raise ValueError(f"wrong number of rows: {len(s)}")

  output = b""
  for col in range(0, cols):
    for row in range(0, 3):
      byte = ""
      for bit in range(0, 8):
        y = row * 8 + bit
        if y >= rows:
          byte += "0"
        else:
          byte += "0" if s[y][col] == " " else "1"
      output += bytes([int(byte, 2)])
  return output

def prt_char(char, cols=12, times=1):
  prt([0x1b, b"&", 3, b"A", b"A"])
  prt([cols])
  prt(char)
  prt([0x1b, b"%", 1])
  for x in range(0, times):
    prt(b"A")
  prt([0x1b, b"%", 0])


pf_1act_a = mkchar(12, 24,
    "            "  #  0
    "            "  #  1
    "            "  #  2
    "            "  #  3
    "            "  #  4
    "            "  #  5
    "     xx     "  #  6
    "    xxxx    "  #  7
    "   xxxxxx   "  #  8
    "    xxxxxx  "  #  9
    " xx  xxxxxx "  # 10
    "xxxx  xxxxxx"  # 11
    "xxxx  xxxxxx"  # 12
    " xx  xxxxxx "  # 13
    "    xxxxxx  "  # 14
    "   xxxxxx   "  # 15
    "    xxxx    "  # 16
    "     xx     "  # 17
    "            "  # 18
    "            "  # 19
    "            "  # 20
    "            "  # 21
    "            "  # 22
    "            "  # 23
    )
pf_1act_b = mkchar(12, 24,
    "            "  #  0
    "            "  #  1
    "            "  #  2
    "            "  #  3
    "            "  #  4
    "            "  #  5
    "            "  #  6
    "            "  #  7
    "            "  #  8
    "     xx     "  #  9
    "    xxxx    "  # 10
    "   xxxxxx   "  # 11
    "    xxxxxx  "  # 12
    " xx  xxxxxx "  # 13
    "xxxx  xxxxxx"  # 14
    "xxxx  xxxxxx"  # 15
    " xx  xxxxxx "  # 16
    "    xxxxxx  "  # 17
    "   xxxxxx   "  # 18
    "    xxxx    "  # 19
    "     xx     "  # 20
    "            "  # 21
    "            "  # 22
    "            "  # 23
    )
box12 = mkchar(12, 24,
    "xxxxxxxxxxxx"  #  0
    "x          x"  #  1
    "x          x"  #  2
    "x          x"  #  3
    "x          x"  #  4
    "x          x"  #  5
    "x          x"  #  6
    "x          x"  #  7
    "x          x"  #  8
    "x          x"  #  9
    "x          x"  # 10
    "x          x"  # 11
    "x          x"  # 12
    "x          x"  # 13
    "x          x"  # 14
    "x          x"  # 15
    "x          x"  # 16
    "x          x"  # 17
    "x          x"  # 18
    "x          x"  # 19
    "x          x"  # 20
    "x          x"  # 21
    "x          x"  # 22
    "xxxxxxxxxxxx"  # 23
    )
box9 = mkchar(9, 24,
    "xxxxxxxxx"  #  0
    "x       x"  #  1
    "x       x"  #  2
    "x       x"  #  3
    "x       x"  #  4
    "x       x"  #  5
    "x       x"  #  6
    "x       x"  #  7
    "x       x"  #  8
    "x       x"  #  9
    "x       x"  # 10
    "x       x"  # 11
    "x       x"  # 12
    "x       x"  # 13
    "x       x"  # 14
    "x       x"  # 15
    "x       x"  # 16
    "x       x"  # 17
    "x       x"  # 18
    "x       x"  # 19
    "x       x"  # 20
    "x       x"  # 21
    "x       x"  # 22
    "xxxxxxxxx"  # 23
    )
blank_char = bytes([0] * 36)

pf_fntb_act1 = Udchars("*   ", 9, 24,
    #0         0         0         012345
    "                                    "  #  0
    "                                    "  #  1
    "                                    "  #  2
    "                                    "  #  3
    "                                    "  #  4
    "                                    "  #  5
    "                                    "  #  6
    "       x                            "  #  7
    "      xxx                           "  #  8
    "     xxxxx                          "  #  9
    "    xxxxxxx                         "  # 10
    "   xxxxxxxxx                        "  # 11
    "    xxxxxxxxx                       "  # 12
    " xx  xxxxxxxxx                      "  # 13
    "xxxx  xxxxxxxxx                     "  # 14
    "xxxx  xxxxxxxxx                     "  # 15
    " xx  xxxxxxxxx                      "  # 16
    "    xxxxxxxxx                       "  # 17
    "   xxxxxxxxx                        "  # 18
    "    xxxxxxx                         "  # 19
    "     xxxxx                          "  # 20
    "      xxx                           "  # 21
    "       x                            "  # 22
    "                                    "  # 23
    )
pf_fntb_act2 = Udchars("**  ", 9, 24,
    #0         0         0         012345
    "                                    "  #  0
    "                                    "  #  1
    "                                    "  #  2
    "                                    "  #  3
    "                                    "  #  4
    "                                    "  #  5
    "                                    "  #  6
    "       x                            "  #  7
    "      xxx        x                  "  #  8
    "     xxxxx      xxx                 "  #  9
    "    xxxxxxx    xxxxx                "  # 10
    "   xxxxxxxxx  xxxxxxx               "  # 11
    "    xxxxxxxxx  xxxxxxx              "  # 12
    " xx  xxxxxxxxx  xxxxxxx             "  # 13
    "xxxx  xxxxxxxxx  xxxxxxx            "  # 14
    "xxxx  xxxxxxxxx  xxxxxxx            "  # 15
    " xx  xxxxxxxxx  xxxxxxx             "  # 16
    "    xxxxxxxxx  xxxxxxx              "  # 17
    "   xxxxxxxxx  xxxxxxx               "  # 18
    "    xxxxxxx    xxxxx                "  # 19
    "     xxxxx      xxx                 "  # 20
    "      xxx        x                  "  # 21
    "       x                            "  # 22
    "                                    "  # 23
    )
pf_fntb_act3 = Udchars("*** ", 9, 24,
    #0         0         0         012345
    "                                    "  #  0
    "                                    "  #  1
    "                                    "  #  2
    "                                    "  #  3
    "                                    "  #  4
    "                                    "  #  5
    "                                    "  #  6
    "       x                            "  #  7
    "      xxx        x                  "  #  8
    "     xxxxx      xxx       x         "  #  9
    "    xxxxxxx    xxxxx     xxx        "  # 10
    "   xxxxxxxxx  xxxxxxx  xxxxxx       "  # 11
    "    xxxxxxxxx  xxxxxxx  xxxxxx      "  # 12
    " xx  xxxxxxxxx  xxxxxxx  xxxxxx     "  # 13
    "xxxx  xxxxxxxxx  xxxxxxx  xxxxxx    "  # 14
    "xxxx  xxxxxxxxx  xxxxxxx  xxxxxx    "  # 15
    " xx  xxxxxxxxx  xxxxxxx  xxxxxx     "  # 16
    "    xxxxxxxxx  xxxxxxx  xxxxxx      "  # 17
    "   xxxxxxxxx  xxxxxxx  xxxxxx       "  # 18
    "    xxxxxxx    xxxxx     xxx        "  # 19
    "     xxxxx      xxx       x         "  # 20
    "      xxx        x                  "  # 21
    "       x                            "  # 22
    "                                    "  # 23
    )


p.set_with_default(font="a")
p.text("01234567890\n")
prt_char(box12, times=10)
p.text(" 12\n")

p.set(font="b")
p.text("01234567890\n")
prt_char(blank_char, times=0)

prt_char(box9, cols=9, times=10)
p.text(" 9\n")

pf_fntb_act1.print_to_printer(p, "b")
p.text(" 1 action\n")
pf_fntb_act2.print_to_printer(p, "b")
p.text(" 2 actions\n")
pf_fntb_act3.print_to_printer(p, "b")
p.text(" 3 actions\n")

p.cut()

if not ARGS.print_addr:
  print(p.output)
