#!/usr/bin/env python
import sys
from args import ARGS
from escpos import printer
from pf_icons import ACTIONS_FREE, ACTIONS_1, ACTIONS_2, ACTIONS_3
from udchar import Udchars

ARGS.add_argument("--profile", dest='print_profile', default="TM-T88II")
ARGS.add_argument("--printer", dest='print_addr')

if ARGS.print_addr:
  p = printer.Network(ARGS.print_addr, profile=ARGS.print_profile)
else:
  p = printer.Dummy(profile=ARGS.print_profile)

BOX12 = Udchars("█", 12, 24,
    "xxxxxxxxxxxx"  #  0
    "x          x"  #  1
    "x          x"  #  2
    "x          x"  #  3
    "x          x"  #  4
    "x          x"  #  5
    "x          x"  #  6
    "x          x"  #  7
    "x          x"  #  8
    "x          x"  #  9
    "x          x"  # 10
    "x          x"  # 11
    "x          x"  # 12
    "x          x"  # 13
    "x          x"  # 14
    "x          x"  # 15
    "x          x"  # 16
    "x          x"  # 17
    "x          x"  # 18
    "x          x"  # 19
    "x          x"  # 20
    "x          x"  # 21
    "x          x"  # 22
    "xxxxxxxxxxxx"  # 23
    )
BOX9 = Udchars("█", 9, 24,
    "xxxxxxxxx"  #  0
    "x       x"  #  1
    "x       x"  #  2
    "x       x"  #  3
    "x       x"  #  4
    "x       x"  #  5
    "x       x"  #  6
    "x       x"  #  7
    "x       x"  #  8
    "x       x"  #  9
    "x       x"  # 10
    "x       x"  # 11
    "x       x"  # 12
    "x       x"  # 13
    "x       x"  # 14
    "x       x"  # 15
    "x       x"  # 16
    "x       x"  # 17
    "x       x"  # 18
    "x       x"  # 19
    "x       x"  # 20
    "x       x"  # 21
    "x       x"  # 22
    "xxxxxxxxx"  # 23
    )


p.set_with_default(font="a")
p.text("01234567890\n")
BOX12.print_to_printer(p, "a", times=10)
p.text(" 12\n")

p.set(font="b")
p.text("01234567890\n")
BOX9.print_to_printer(p, "b", times=10)
p.text(" 9\n")

ACTIONS_FREE.print_to_printer(p, "b")
p.text(" free action\n")
ACTIONS_1.print_to_printer(p, "b")
p.text(" 1 action\n")
ACTIONS_2.print_to_printer(p, "b")
p.text(" 2 actions\n")
ACTIONS_3.print_to_printer(p, "b")
p.text(" 3 actions\n")

p.cut()

if not ARGS.print_addr:
  print(p.output)
